Controllers/UserDatabasesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Centric_Team_3.DAL;
using Centric_Team_3.Models;
using Microsoft.AspNet.Identity;

namespace Centric_Team_3.Controllers
{
    public class UserDatabasesController : Controller
    {
        private context db = new context();

        // GET: UserDatabases
        public ActionResult Index(int? page, string search)
        {
            var user = from u in db.UserDatabase select u;
            user = db.UserDatabase.OrderBy(u => u.lastName).ThenBy(u => u.firstName); ;
            if (!String.IsNullOrEmpty(search))
            {
                user = user.Where(u => u.lastName.Contains(search) || u.firstName.Contains(search));
            }
            var userList = user.ToList();
            return View(userList);
        }

        // GET: UserDatabases/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserDatabase userDatabase = db.UserDatabase.Find(id);
            if (userDatabase == null)
            {
                return HttpNotFound();
            }
            return View(userDatabase);
        }

        // GET: UserDatabases/Create
        [Authorize]
        public ActionResult Create()
        {
            ViewBag.errorMessage = "";
            return View();
        }

        // POST: UserDatabases/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,lastName,firstName,businessUnit,office,startDate")] UserDatabase userDatabase)
        {
            if (ModelState.IsValid && userDatabase.businessUnit != 0 && userDatabase.office != 0) 
            {
                Guid newUser;
                Guid.TryParse(User.Identity.GetUserId(), out newUser);
                userDatabase.ID = newUser;
                db.UserDatabase.Add(userDatabase);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.errorMessage = "Please make sure you have selected your Business Unit and Title";
            return View(userDatabase);

        }

        // GET: UserDatabases/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserDatabase userDatabase = db.UserDatabase.Find(id);
            if (userDatabase == null)
            {
                return HttpNotFound();
            }
            return View(userDatabase);
        }

        // POST: UserDatabases/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,lastName,firstName,businessUnit,office,startDate")] UserDatabase userDatabase)
        {
            if (ModelState.IsValid)
            {
                db.Entry(userDatabase).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(userDatabase);
        }

        // GET: UserDatabases/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserDatabase userDatabase = db.UserDatabase.Find(id);
            if (userDatabase == null)
            {
                return HttpNotFound();
            }
            return View(userDatabase);
        }

        // POST: UserDatabases/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            UserDatabase userDatabase = db.UserDatabase.Find(id);
            db.UserDatabase.Remove(userDatabase);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

    }
}

Views/UserDatabases/Create.cshtml
@model Centric_Team_3.Models.UserDatabase

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@ViewBag.errorMessage 
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>UserDatabase</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.lastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.lastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.lastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.firstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.firstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.firstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.businessUnit, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.businessUnit, "Please Select", htmlAttributes: new { @class = "form-control" })

                @Html.ValidationMessageFor(model => model.businessUnit, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.office, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.office, "Please Select", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.office, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.startDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.startDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.startDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/UserDatabases/Delete.cshtml
@model Centric_Team_3.Models.UserDatabase

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>UserDatabase</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.lastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.lastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.firstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.firstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.businessUnit)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.businessUnit)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.office)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.office)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.startDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.startDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/UserDatabases/Details.cshtml
@model Centric_Team_3.Models.UserDatabase
    @{
        ViewBag.Title = "Details";
    }



    <h2>Details</h2>


    <div>
        <h4>UserDatabase</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.firstName)
            </dt>



            <dd>
                @Html.DisplayFor(model => model.firstName)
            </dd>



            <dt>
                @Html.DisplayNameFor(model => model.lastName)
            </dt>



            <dd>
                @Html.DisplayFor(model => model.lastName)
            </dd>



            <dt>
                @Html.DisplayNameFor(model => model.businessUnit)
            </dt>



            <dd>
                @Html.DisplayFor(model => model.businessUnit)
            </dd>



            <dt>
                @Html.DisplayNameFor(model => model.office)
            </dt>



            <dd>
                @Html.DisplayFor(model => model.office)
            </dd>



            <dt>
                @Html.DisplayNameFor(model => model.startDate)
            </dt>



            <dd>
                @Html.DisplayFor(model => model.startDate)
            </dd>



        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
        @Html.ActionLink("Back to List", "Index")
    </p>

Views/UserDatabases/Edit.cshtml
@model Centric_Team_3.Models.UserDatabase

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>UserDatabase</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.lastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.lastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.lastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.firstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.firstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.firstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.businessUnit, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.businessUnit, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.businessUnit, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.office, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.office, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.office, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.startDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.startDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.startDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/UserDatabases/Index.cshtml
@model IEnumerable<Centric_Team_3.Models.UserDatabase>
@{
    ViewBag.Title = "Index";
}
<br />
<div style="background-color: #fdb825">
    <h2 class="text-center" style="font-size: 50px; color:#2c1a5d"><strong>Centric Consulting Employees</strong></h2>
</div>
<br />
<p>
    @Html.ActionLink("Create New", "Create")
</p>
@using (Html.BeginForm("Index", "UserDatabases", FormMethod.Get))
{
    <p>
        <strong>Find by name:</strong> @Html.TextBox("search")
        <input type="submit" value="Search" />
    </p>
}
<br />
<table class="table table-striped table-bordered table-condensed">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.firstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.lastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.businessUnit)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.office)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.startDate)
        </th>
        <th></th>
    </tr>



    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.firstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.lastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.businessUnit)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.office)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.startDate)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.ID })
            </td>
        </tr>
    }



</table>